# 对应 -O2 或 -O3
# CONFIG_SPEED_OPTIMIZATIONS=y
# 对应 -Og
CONFIG_DEBUG_OPTIMIZATIONS=y
# 对应 -O0
CONFIG_NO_OPTIMIZATIONS=y
# 对应 -Os 体积优化
# CONFIG_SIZE_OPTIMIZATIONS=y 

# gdb线程感知
CONFIG_DEBUG_THREAD_INFO=y
